# fly.toml app configuration file generated for messagechain-docs on 2023-11-18T21:57:11+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "messagechain-docs"
primary_region = "hkg"

[build]

[http_service]
  internal_port = 3000
  force_https = false
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
